### ISSUE TITLE
Integration keeps losing connection

### ISSUE THREAD

**Issue by Axsgranted** [dcmeglio/homeassistant-petsafe#12]
Integration was working for a couple of weeks flawlessly.  Was asked to reconfigure, which I did assuming maybe there was a 30 day token and now it asks me to reconfigure every 5 minutes.

**Comment by Axsgranted** [comment]
Error Log Details after authenticating successfully and then it "loses" connection:

Logger: custom_components.petsafe
Source: helpers/update_coordinator.py:343
Integration: PetSafe ([documentation](https://github.com/dcmeglio/homeassistant-petsafe/blob/master/README), [issues](https://github.com/dcmeglio/homeassistant-petsafe/issues))
First occurred: 6:53:07 PM (6 occurrences)
Last logged: 7:25:48 PM

Authentication failed while fetching PetSafe data: Client error '403 Forbidden' for url 'https://platform.cloud.petsafe.net/scoopfree/product/product' For more information check: https://httpstatuses.com/403

**Comment by dcmeglio** [comment]
I think they changed something or broke something. It might fix itself but if not it might be best to disable the integration so they don’t lock you out for too many failed attempts.

**Comment by cadwizzard** [comment]
I'm seeing this too. But I was asked to reconfigure again just once (15h ago).
I input email again and got the access code.
Now i have my email address showing twice in the integration, but only one with device and entity behind it.... but all entities are unavailable

**Comment by Axsgranted** [comment]
> I'm seeing this too. But I was asked to reconfigure again just once (15h ago). I input email again and got the access code. Now i have my email address showing twice in the integration, but only one with device and entity behind it.... but all entities are unavailable
> 
> UPDATE: i've since reloaded the integration from menu next to my email address - entities are now live again

I've seen this exact behavior.  I also did a reload and it worked for a little bit then stopped again.

**Comment by Axsgranted** [comment]
Update: I removed the integration and re-added it and it appears to be working normally again.  But when it wasn't, how it handled the issues created the duplicate configuration entries @cadwizzard mentioned.

**Comment by Zeunas** [comment]
Are you guys still having this issue? It just started happening to me ( that I noticed)

**Comment by MivraMe** [comment]
> Are you guys still having this issue? It just started happening to me ( that I noticed)

Yep same here

**Comment by Axsgranted** [comment]
Happening to me again after the latest updates

**Comment by dcmeglio** [comment]
I'm working on a fix for this it's just kind of hard to prove it fixes it since I haven't found a pattern to when the issue occurs.

**Comment by dcmeglio** [comment]
If you want to test out my fix and you know what to do, update the manifest.json for the integration to use petsafe 2.0.7

```
  "requirements": [
    "petsafe==2.0.7"
  ],
```
Since it's kind of a "wait and see" bug having more people let me know if they can see an improvement will help. After changing the file just restart HA

**Comment by ablack89** [comment]
I have been seeing the issue every few days recently - have applied your fix and will report back if I see it happen again.

**Comment by Axsgranted** [comment]
> If you want to test out my fix and you know what to do, update the manifest.json for the integration to use petsafe 2.0.7
> 
> ```
>   "requirements": [
>     "petsafe==2.0.7"
>   ],
> ```
> 
> Since it's kind of a "wait and see" bug having more people let me know if they can see an improvement will help. After changing the file just restart HA

Trying this as well.  The connection usually stays for 5 days or so, so it might be a few days before I can report back.

**Comment by Axsgranted** [comment]
Just lost connection and it wants me to re-authenticate even after setting the requirements version.

**Comment by ablack89** [comment]
I've also had it happen again today, with the updated version.

**Comment by MivraMe** [comment]
Same for me, just lost connection, do we ping the server at a high interval so we are kicked out ?

**Comment by siobhanellis** [comment]
I just lost connection after reconfiguring today

**Comment by dcmeglio** [comment]
Darn happened to me today too. I'll keep investigating.

**Comment by dcmeglio** [comment]
I want to check if you're experiencing the same thing I am while yes I am getting a 403 that causes a reauth, it does seem the data is continuing to update? I'm wondering if there API is just a bit flaky and throws 403s sometimes and I just need to add retries. Seems like an odd thing, but it does appear my litter box is still updating even though I got that error.

**Comment by ablack89** [comment]
Yes, if I ignore the re-auth prompts the data keeps coming in for me.

**Comment by MivraMe** [comment]
No data for me... and it's seem to create a new device every time.. 
![image](https://github.com/user-attachments/assets/51b541e1-25f2-4cbe-9c24-78bb45f20cc3)

**Comment by dcmeglio** [comment]
@MivraMe the duplicate items is a different bug, I'll look into that, but this sounds like you did the reauth. It seems if you ignore the reauth, everything continues to work.

**Comment by MivraMe** [comment]
All my sensors are unavailable for my petsafe food..

**Comment by dcmeglio** [comment]
Right, as I said, you did the reauth workflow, correct? That is causing the bug I just filed on your behalf #18. If you delete the devices and reinstall it should begin working again.

**Comment by dcmeglio** [comment]
I've been testing a fix for this that so far seems good. If it's still working this weekend I'll release a new version

**Comment by dcmeglio** [comment]
I ran this for a week and didn't have any auth issues or data issues. I think their API just occasionally throws 403s so I added some retries to detect multiple errors before triggering a reauth can you guys try out 1.3.5 and let me know if it works? https://github.com/dcmeglio/homeassistant-petsafe/releases/tag/1.3.5

**Comment by ablack89** [comment]
Thanks, have updated and will report back if I see any issue.

**Comment by dcmeglio** [comment]
I haven't heard any further reports so I'm going to mark this as closed.
