### ISSUE TITLE
petsafe lib creates a new httpx client for every api call

### ISSUE THREAD

**Issue by bdraco** [dcmeglio/homeassistant-petsafe#15]
https://github.com/dcmeglio/petsafe/blob/cea8dc29ad4890c29918a695a1d0a1a1b4a612f3/petsafe/client.py#L184

This is very expensive.

**Comment by dcmeglio** [comment]
Yup, I'll be working on this this weekend. Still really surprised why the issue only became noticeable recently? This code hasn't changed but it seems there are now significant CPU impacts

**Comment by dcmeglio** [comment]
Not sure if this will fix the performance issues people are seeing yet, but I pushed a fix for this issue to use `get_async_client` instead.
