### ISSUE TITLE
Feeding Paused switch needs multiple toggles to change state

### ISSUE THREAD

**Issue by hanscats** [dcmeglio/homeassistant-petsafe#2]
Thank you for making this integration!

I have a [Smart Feed Automatic Dog and Cat Feeder, 2nd Generation](https://store.petsafe.net/smart-feed) with firmware: V2.0.9

It works as intended, but the only issue I have is that the Feeding Paused switch needs multiple toggles to change state.

Please advice how to debug / print debug log if needed.

**Comment by dcmeglio** [comment]
I suspect it is related to polling grabbing the "old" value. If you just toggle it once but then wait, does it eventually get in the correct state?

**Comment by hanscats** [comment]
You are probably right. After multiple tests it get in the correct state after about 15 seconds.

**Comment by dcmeglio** [comment]
I'll see if there is a way I can handle that better. Still learning how to build HA integrations so I may have done something wrong!

**Comment by hanscats** [comment]
I am cheering for you!
Feel free to close this issue 👍🏻
