### ISSUE TITLE
Home Assistant services don't work for first generation Smart Feeder

### ISSUE THREAD

**Issue by cmccambridge** [dcmeglio/homeassistant-petsafe#4]
Hello!

I _believe_ I have a first generation PetSafe Smart Feeder, purchased in 2018, and that it has an interesting discrepancy versus the second generation: My feeder _doesn't have_ a `product_name` in its JSON device object from the `smart-feed/feeders` API endpoint. (See below)

This causes all of the scheduling services to fail, as well as causing the service `target` to show empty lists for Areas containing a feeder and the Devices list itself. 🐛 

Following that root cause forward, the fallout in code is:
* in `petsafe` library: `petsafe.devices.DeviceSmartFeed.product_name` is `None`
* in the HA integration: each `PetSafeFeederXXXXEntity` sets up its device info with `model = None`
* ...so, `is_device_feeder` always returns `False` since the model doesn't match `"SmartFeed_2.0"`
* ...so, `get_feeders_by_device_id` returns an empty list
* ...so, `get_feeders_for_services` returns an empty list
* ...so, each of the service handlers fails to take any action, as they have no devices to act on!

Here's my full JSON result from `smart-feed/feeders`, having replaced only the `id` and `thing_name`:
```
[
    {
        "id": 12345,
        "serial": null,
        "thing_name": "a-123456789abc",
        "battery_voltage": "24698",
        "region": "",
        "connection_status": 2,
        "is_food_low": 0,
        "is_adapter_installed": true,
        "is_batteries_installed": true,
        "firmware_version": "V1.1.0.9",
        "product_name": null,
        "revision_desired": 325,
        "revision_reported": 325,
        "food_sensor_current": 0,
        "food_sensor_reference": 0,
        "network_snr": 58,
        "network_rssi": -32,
        "connection_status_timestamp": "2023-01-12T14:46:47.000Z",
        "created_at": "2018-11-14 00:54:36",
        "settings": {
            "friendly_name": "Food Robot",
            "paused": false,
            "slow_feed": true,
            "child_lock": true,
            "notify_on_feed": true,
            "notify_on_connection_state_change": true,
            "notify_on_low_food": true,
            "notify_on_empty_food": true,
            "notify_on_error": true,
            "notify_on_community_message": true,
            "timezone": "America/Chicago",
            "pet_type": "cat",
            "updated_at": "2022-08-06 12:45:04"
        },
        "schedules": [
            {
                "id": 253178,
                "amount": 2,
                "time": "06:00",
                "updated_at": "2022-11-06 07:03:34"
            }
        ]
    }
]
```

**Comment by cmccambridge** [comment]
Couple ideas on fixes...
1. Could hardcode a fallback, for the sake of simplicity: if `product_name == null`, then simply hard code `SmartFeed_2.0` as the model. This passes all the checks, restoring selector and service functionality... but may be slightly misleading to HA users who know that theirs is a gen 1 feeder.
2. Could make up a model value, e.g. `SmartFeed_1.0`, and assign it any time `product_name == null and firmware_version == V1.1.0.9`. This would provide a little nicer data, but I have no idea whether the firmware my device reports is the only gen1 firmware...

**Comment by dcmeglio** [comment]
Sorry forgot about this PR, I'll get this merged in this week

**Comment by cmccambridge** [comment]
No worries at all! Thanks :-)
