### ISSUE TITLE
Change Feed amount 

### ISSUE THREAD

**Issue by blakeshelley5** [dcmeglio/homeassistant-petsafe#7]
How do change the manual feed amount from 1/8 to 1 cup?

**Comment by dcmeglio** [comment]
Update to 1.3.0 (just released) which has a feed service that allows you to specify the amount.

**Comment by blakeshelley5** [comment]
Hi, I really appreciate your work on this. Can you please send instructions
on how to change it? The edits I'm making to the yaml aren't working.

**Comment by dcmeglio** [comment]
Sorry, not sure what you're talking about. What yaml? you just need to call the service.
